services:
  shortenator_postgres_test:
    image: postgres:17-alpine
    container_name: shortenator_postgres_test
    restart: 'no'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER']
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env.test
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5444:5432'
    volumes:
      - shortenator_test:/var/lib/postgresql/data

  shortenator_redis_test:
    image: redis:alpine
    container_name: shortenator_redis_test
    ports:
      - '6380:6379'
    volumes:
      - shortenator_redis_test:/data

networks:
  default:
    name: shortenator_test

volumes:
  shortenator_postgres_test:
  shortenator_redis_test:
