services:
  nestjs_starter_postgress: # Update to match project name
    image: postgres:17-alpine
    container_name: nestjs_starter_postgres # Update to match project name
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - nestjs_starter_postgres_data:/var/lib/postgresql/data # Update

  nestjs_starter_redis: # Update to match project name
    image: redis:alpine
    container_name: nestjs_starter_redis # Update to match project name
    ports:
      - '6380:6379'
    volumes:
      - nestjs_starter_redis_data:/data #Update

networks:
  default:
    name: nestjs_starter

volumes:
  nestjs_starter_postgres_data: # Update
  nestjs_starter_redis_data: # Update
