services:
  shortenator_postgress: # Update to match project name
    image: postgres:17-alpine
    container_name: shortenator_postgres # Update to match project name
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - shortenator_postgres_data:/var/lib/postgresql/data # Update

  shortenator_redis: # Update to match project name
    image: redis:alpine
    container_name: shortenator_redis # Update to match project name
    ports:
      - '6380:6379'
    volumes:
      - shortenator_redis_data:/data #Update

networks:
  default:
    name: shortenator

volumes:
  shortenator_postgres_data: # Update
  shortenator_redis_data: # Update
